# Generated by Django 2.0.5 on 2018-05-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artiste',
            new_name='artist',
        ),
    ]
