# Generated by Django 2.0.5 on 2018-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180516_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_fav2',
            field=models.BooleanField(default=False),
        ),
    ]
